#! /bin/bash

if [ -z "$1" ] 
then
	echo "no unzip folder given"
	echo "Usage: make folderToUnzip"
	exit 2
fi

source=$1

echo "starting..."

# Unzip folder and get new name
unzip -q $source
source="${source%.*}"

# Read in each filename in folder
for file in "$source"/*;
do
	set student
	set fileName
    read student fileName <<< $(gawk -F_ '{printf "%s %s", $2, $5}' <<< "${file}")
	mkdir -p "$source"/"$student"
	if [ -n "$fileName" ] 
	then
		mv "$file" "$source"/"$student"/"$fileName"
	else
		mv "$file" "$source"/"$student"/"memo.txt"
	fi
done

echo "created folder structure, now testing students..."

report="report"
echo "Running tests for students" > "$report"
for folder in "$source"/*
do
	make -f ../../makefile -C "$folder" >> "$report"
	make test -f ../../makefile -C "$folder" >> "$report"
done

echo "done"
